name: Deploy to FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          ftp-server: ${{ secrets.HOSTINGER_FTP_URL }}
          ftp-username: ${{ secrets.HOSTINGER_FTP_USERNAME }}
          ftp-password: ${{ secrets.HOSTINGER_FTP_PASSWORD }}
          local-dir: ./dist
          server-dir: /
