name: Deploy Astro Site to Hostinger

# Trigger the action on push to the main branch
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # Use GitHub-hosted Ubuntu environment

    steps:
    # Step 1: Checkout the latest code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Node.js environment to build the Astro site
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    # Step 3: Install dependencies and build the site
    - name: Install dependencies and build
      run: |
        npm ci
        npm run build

    # Step 4: Deploy to Hostinger via FTP
    - name: Deploy to Hostinger
      uses: SamKirkland/FTP-Deploy-Action@v4.3.0 
      with:
        server: ${{ secrets.HOSTINGER_SERVER }}
        username: ${{ secrets.HOSTINGER_USERNAME }}
        password: ${{ secrets.HOSTINGER_PASSWORD }}
        local-dir: ./dist # Directory with the built Astro site
        server-dir: /public_html/ # Directory on Hostinger where files should be uploaded
