name: Deploy to FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/setup-node@v4

      - name: Install pnpm
        run: npm i -g pnpm

      - name: Install dependencies
        run: pnpm i

      - name: Build
        run: pnpm build

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          ftp-server: ${{ secrets.HOSTINGER_SERVER }}
          ftp-username: ${{ secrets.HOSTINGER_USERNAME }}
          ftp-password: ${{ secrets.HOSTINGER_PASSWORD }}
          local-dir: ./dist
          server-dir: /
