name: Deploy on push

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      CONTENT_API: ${{ secrets.CONTENT_API }}
      FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
      FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
      FTP_HOST: ${{ secrets.FTP_HOST }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js and PNPM
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - run: npm i -g pnpm
      - run: pnpm i

      - name: Build
        run: pnpm build

      - name: Upload to FTP
        run: |
          ftp -n $FTP_HOST <<END_SCRIPT
          quote USER $FTP_USERNAME
          quote PASS $FTP_PASSWORD
          cd /
          mput -r *
          quit
          END_SCRIPT
